on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  releases-linux:
    name: Release Go Binary for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      goos: linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        run: go build
        env:
          GOOS: ${{ env.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: Compress
        run: tar -zcvf zenv-${{ github.ref_name }}-${{ env.goos }}-${{ matrix.goarch }}.tar.gz zenv
      - uses: softprops/action-gh-release@v2
        with:
          files: zenv-${{ github.ref_name }}-${{ env.goos }}-${{ matrix.goarch }}.tar.gz

  releases-macos:
    name: Release Go Binary for MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Build
        run: go build
        env:
          GOOS: ${{ env.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
      - name: Compress
        run: tar -zcvf zenv-${{ github.ref_name }}-${{ env.goos }}-${{ matrix.goarch }}.tar.gz zenv
      - uses: softprops/action-gh-release@v2
        with:
          files: zenv-${{ github.ref_name }}-${{ env.goos }}-${{ matrix.goarch }}.tar.gz
